### ISSUE TITLE
Crash on play

### ISSUE THREAD

**Issue by richardmalone** [bembidiona/bandonautica#1]
Hi,

Nice app, I used to use the python 'bandcamp-player' but since that no longer works I have been looking for an alternative.

When I press play it does some thinking and then crashes to desktop.  The log file is as follows:

```
-- RETRIEVE RANDOM SONG --
retrieving random quantum numbers...
WARNING: QRNG site isn't responding. Probably Australia is on fire again :( Fallback to pseudo-random...
randomArtistPage: https://thembloodyroyals.bandcamp.com/music
artist_name: Them Bloody Royals
link_to_release: https://thembloodyroyals.bandcamp.com/track/you-are-coralline
local variable 'track_name' referenced before assignment
```

Thanks

**Comment by bembidiona** [comment]
Thank you for reporting, it was a know issue! Luckily for you in the last days I updated the app, and right now I am uploading the changes (and a new release for windows).
I hope this new version works for you too!

**Comment by richardmalone** [comment]
Awesome, works great. Thank you!
